spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: shiftcontrol
    password: password
  jpa:
    hibernate:
      ddl-auto: none

trust:
  rabbitmq:
    exchange: shiftcontrol
    queue: trust-alert-service
    routing-key: shiftcontrol.#
