server:
  port: 8089
spring:
    application:
        name: auditlog-service
    rabbitmq:
      addresses: rabbitmq:5672
      username: shiftcontrol
      password: password
    jpa:
      properties:
        hibernate:
          type:
            json_format_mapper: jsonb
logging:
  level:
    'org.hibernate.orm.connections.pooling': WARN

audit:
  rabbitmq:
    exchange: shiftcontrol
    queue: auditlog
    routingKey: '#'
