spring:
  rabbitmq:
    addresses: rabbitmq:5672
    username: shiftcontrol
    password: password
  jackson:
    default-property-inclusion: non_null
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.127.0.0.1.nip.io/realms/dev
keycloak:
    auth-server-url: http://keycloak.127.0.0.1.nip.io/
    auth-realm: dev
    allowed-issuers:
      - http://keycloak.127.0.0.1.nip.io/realms/dev
      - http://keycloak:8080/realms/dev
    client:
      id: admin-cli
      realm: master
      username: admin
      password: admin

management:
  otlp:
    metrics:
      export:
        enabled: false

pretalx:
  locale: en
  sync:
    cron: "0 0/5 * * * *" # every 5 minutes
